import type { DemoRecommendationSummary } from '@/types/recommendation'

// 17 recommendations totaling exactly $3,284/month
// EC2_UNDERUTILIZED (8): $1,576
// EC2_RIGHTSIZING (4): $1,048
// S3_STORAGE_OPTIMIZATION (3): $508
// NAT_GATEWAY_OPTIMIZATION (2): $152
// Total: $3,284

export const DEMO_RECOMMENDATIONS: DemoRecommendationSummary = {
  total_estimated_savings: 3284.00,
  recommendations: [
    // ── EC2 Rightsizing ─────────────────────────────────────────────
    {
      id: 'rec-001',
      resource_id: 'i-0a1b2c3d4e5f00015',
      resource_name: 'prod-analytics-01',
      type: 'EC2_RIGHTSIZING',
      severity: 'high',
      reason: 'Average CPU utilization is 18.4% over 14 days on m5.4xlarge. Rightsizing to m5.2xlarge reduces cost by 50% with minimal risk at this utilization level.',
      estimated_savings: 412.00,
      detail: 'Current: m5.4xlarge ($554/mo) → Recommended: m5.2xlarge ($277/mo)',
    },
    // ── EC2 Underutilized ────────────────────────────────────────────
    {
      id: 'rec-002',
      resource_id: 'i-0a1b2c3d4e5f00023',
      resource_name: 'ml-experiment-01',
      type: 'EC2_UNDERUTILIZED',
      severity: 'high',
      reason: 'Average CPU utilization is 2.3% over the past 14 days. Instance has been running for 47 days. Likely an idle experiment environment.',
      estimated_savings: 312.00,
      detail: 'Instance type: m5.2xlarge · Running: 47 days · Avg CPU: 2.3%',
    },
    {
      id: 'rec-003',
      resource_id: 'i-0a1b2c3d4e5f00016',
      resource_name: 'prod-analytics-02',
      type: 'EC2_RIGHTSIZING',
      severity: 'medium',
      reason: 'Average CPU utilization is 21.3% over 14 days on m5.2xlarge. Consider rightsizing to m5.xlarge.',
      estimated_savings: 290.00,
      detail: 'Current: m5.2xlarge ($277/mo) → Recommended: m5.xlarge ($139/mo)',
    },
    {
      id: 'rec-004',
      resource_id: 'i-0a1b2c3d4e5f00019',
      resource_name: 'batch-worker-07',
      type: 'EC2_UNDERUTILIZED',
      severity: 'high',
      reason: 'Average CPU utilization is 4.8% over the past 14 days. Instance has been running for 63 days with no sign of batch activity.',
      estimated_savings: 286.00,
      detail: 'Instance type: m5.xlarge · Running: 63 days · Avg CPU: 4.8%',
    },
    {
      id: 'rec-005',
      resource_id: 'i-0a1b2c3d4e5f00021',
      resource_name: 'dev-worker-01',
      type: 'EC2_UNDERUTILIZED',
      severity: 'high',
      reason: 'Average CPU utilization is 6.1% over the past 14 days. Running for 54 days in a development environment.',
      estimated_savings: 244.00,
      detail: 'Instance type: m5.large · Running: 54 days · Avg CPU: 6.1%',
    },
    {
      id: 'rec-006',
      resource_id: 'i-0a1b2c3d4e5f00020',
      resource_name: 'dev-api-01',
      type: 'EC2_UNDERUTILIZED',
      severity: 'high',
      reason: 'Average CPU utilization is 3.2% over the past 14 days. Instance has been running for 89 days in a dev environment.',
      estimated_savings: 198.00,
      detail: 'Instance type: t3.large · Running: 89 days · Avg CPU: 3.2%',
    },
    // ── S3 Storage ──────────────────────────────────────────────────
    {
      id: 'rec-007',
      resource_id: 'analytics-archive',
      resource_name: 'analytics-archive',
      type: 'S3_STORAGE_OPTIMIZATION',
      severity: 'medium',
      reason: '8.4 TB stored with low access frequency. Migrating to S3 Intelligent-Tiering or Glacier Instant Retrieval could reduce storage costs by ~40%.',
      estimated_savings: 192.00,
      detail: 'Size: 8,421 GB · Access pattern: Infrequent · Region: us-east-1',
    },
    {
      id: 'rec-008',
      resource_id: 'i-0a1b2c3d4e5f00018',
      resource_name: 'reporting-svc-01',
      type: 'EC2_RIGHTSIZING',
      severity: 'high',
      reason: 'Average CPU utilization is 19.2% over 14 days on r5.2xlarge. This memory-optimized instance type is overprovisioned for current workload.',
      estimated_savings: 168.00,
      detail: 'Current: r5.2xlarge ($365/mo) → Recommended: r5.xlarge ($183/mo)',
    },
    // ── S3 / EC2 continued ──────────────────────────────────────────
    {
      id: 'rec-009',
      resource_id: 'ml-training-data',
      resource_name: 'ml-training-data',
      type: 'S3_STORAGE_OPTIMIZATION',
      severity: 'low',
      reason: '6.1 TB of ML training data with infrequent access. Consider S3 Glacier Instant Retrieval for datasets not accessed in the past 90 days.',
      estimated_savings: 156.00,
      detail: 'Size: 6,128 GB · Access pattern: Infrequent · Region: us-east-1',
    },
    {
      id: 'rec-010',
      resource_id: 'i-0a1b2c3d4e5f00025',
      resource_name: 'legacy-service-01',
      type: 'EC2_UNDERUTILIZED',
      severity: 'high',
      reason: 'Average CPU utilization is 8.9% over the past 14 days. Instance has been running for 112 days. Investigate if this service is still active.',
      estimated_savings: 152.00,
      detail: 'Instance type: m5.xlarge · Running: 112 days · Avg CPU: 8.9%',
    },
    {
      id: 'rec-011',
      resource_id: 'i-0a1b2c3d4e5f00022',
      resource_name: 'test-runner-01',
      type: 'EC2_UNDERUTILIZED',
      severity: 'medium',
      reason: 'Average CPU utilization is 7.8% over the past 14 days. Test runner instance running continuously for 38 days.',
      estimated_savings: 148.00,
      detail: 'Instance type: c5.large · Running: 38 days · Avg CPU: 7.8%',
    },
    // ── NAT Gateway ─────────────────────────────────────────────────
    {
      id: 'rec-012',
      resource_id: 'nat-gw-prod-1',
      resource_name: 'nat-gw-prod-1',
      type: 'NAT_GATEWAY_OPTIMIZATION',
      severity: 'medium',
      reason: 'NAT Gateway in us-east-1 shows data processing volume below typical thresholds. Review routing rules and consider consolidating with existing NAT infrastructure.',
      estimated_savings: 96.00,
      detail: 'Region: us-east-1 · Monthly data processed: ~180 GB',
    },
    {
      id: 'rec-013',
      resource_id: 'i-0a1b2c3d4e5f00024',
      resource_name: 'sandbox-01',
      type: 'EC2_UNDERUTILIZED',
      severity: 'high',
      reason: 'Average CPU utilization is 5.5% over the past 14 days. Sandbox environment running for 71 days.',
      estimated_savings: 174.00,
      detail: 'Instance type: t3.large · Running: 71 days · Avg CPU: 5.5%',
    },
    {
      id: 'rec-014',
      resource_id: 'i-0a1b2c3d4e5f00017',
      resource_name: 'data-processing-01',
      type: 'EC2_RIGHTSIZING',
      severity: 'medium',
      reason: 'Average CPU utilization is 16.9% over 14 days on c5.2xlarge. Rightsizing to c5.xlarge would reduce compute cost while maintaining headroom.',
      estimated_savings: 178.00,
      detail: 'Current: c5.2xlarge ($245/mo) → Recommended: c5.xlarge ($123/mo)',
    },
    {
      id: 'rec-015',
      resource_id: 'data-lake-backup',
      resource_name: 'data-lake-backup',
      type: 'S3_STORAGE_OPTIMIZATION',
      severity: 'medium',
      reason: '4.2 TB backup data in Standard storage class with no documented access in 180+ days. Lifecycle policy to Glacier would reduce costs significantly.',
      estimated_savings: 160.00,
      detail: 'Size: 4,219 GB · Access pattern: Archival · Region: us-west-2',
    },
    {
      id: 'rec-016',
      resource_id: 'nat-gw-staging',
      resource_name: 'nat-gw-staging',
      type: 'NAT_GATEWAY_OPTIMIZATION',
      severity: 'low',
      reason: 'Staging NAT Gateway shows minimal traffic. Consider replacing with NAT instance or routing through the production NAT Gateway during staging hours.',
      estimated_savings: 56.00,
      detail: 'Region: us-west-2 · Monthly data processed: ~48 GB',
    },
    {
      id: 'rec-017',
      resource_id: 'i-0a1b2c3d4e5f00034',
      resource_name: 'zookeeper-01',
      type: 'EC2_UNDERUTILIZED',
      severity: 'low',
      reason: 'Average CPU utilization is 8.4% over the past 14 days. Verify if this ZooKeeper instance is actively used before stopping.',
      estimated_savings: 62.00,
      detail: 'Instance type: t3.medium · Running: 94 days · Avg CPU: 8.4%',
    },
  ],
}

export const DEMO_RECOMMENDATION_SUMMARY = DEMO_RECOMMENDATIONS
